remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Zete Dai's Portfolio]
description: [Lists projects that I've done in the past]
show_downloads: [false]